#------------------------------------------------------------------------------
# usage: Use tutor to enable the Open edX Xqueue service plugin
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable Xqueue plugin
description: Github Action to install and enable the Tutor plugin - Open edX Xqueue service
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namesapce to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    # retrieve the MySQL connection parameters that we created in Terraform
    # and then stored in Kubernetes secrets. These include:
    #   MYSQL_HOST: mysql.app.mrionline.com
    #   MYSQL_PORT: "3306"
    #   XQUEUE_MYSQL_USERNAME: openedx
    #   XQUEUE_MYSQL_PASSWORD: **************
    #   MYSQL_ROOT_USERNAME: root
    #   MYSQL_ROOT_PASSWORD: *************
    - name: fetch MySQL configuration from Kubernetes secrets
      id: get-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.0
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: mysql-xqueue

    - name: Enable the Xqueue plugin
      id: install-plugin
      shell: bash
      run: pip install tutor-xqueue

    - name: Enable the Xqueue plugin
      id: save-config
      shell: bash
      run: |-
        tutor plugins enable xqueue
        tutor config save
